name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.COMMUNITY_TOKEN }}
        issue-message: "<h1>It's great having you contribute to this project</h1> Welcome to the community :nerd_face:"
        pr-message: "<h1>It's great having you contribute to this project</h1> Welcome to the community :nerd_face: Thanks for giving your time to contribute to <b>Typing Test</b> Project."
